scalatest/README.md

Provided example is somewhat dated. I've stuck in compilation errors while trying to follow it. Changes are simple but not so evident. At least for such a newbie in Scala development as me (I'd known nothing about self-types till this day :) )

ScalaTest example is slightly changed to fix compilation errors

---

library/build.sbt
project/common.scala
specs2/build.sbt
specs2/src/main/scala/jetty/Served.scala
specs2/src/main/scala/netty/Served.scala

Updates specs2 version to latest available.

updates specs2 version

---

library/build.sbt
project/common.scala
specs2/build.sbt
specs2/src/main/scala/jetty/Served.scala
specs2/src/main/scala/netty/Served.scala

Reverts unfiltered/unfiltered#306

Revert "updates specs2 version"

---

json4s/build.sbt
netty-server/src/main/scala/NotFoundHandler.scala
netty-server/src/main/scala/PortBinding.scala
netty-server/src/main/scala/Server.scala
netty-server/src/main/scala/resources.scala
netty-uploads/src/main/scala/request/decoder.scala
netty-websockets/src/main/scala/package.scala
netty-websockets/src/main/scala/plans.scala
netty/build.sbt
netty/src/main/scala/bindings.scala
project/common.scala

This PR updates the 0.9.0 branch to netty 4.1.

Update to netty 4.1.

---

agents/build.sbt
build.sbt
directives/build.sbt
filter-async/build.sbt
filter-uploads/build.sbt
filter/build.sbt
json4s/build.sbt
library/build.sbt
mac/build.sbt
netty-server/build.sbt
netty-uploads/build.sbt
netty-websockets/build.sbt
netty/build.sbt
oauth/build.sbt
oauth2/build.sbt
project/build.properties
project/build.scala
project/plugins.sbt
specs2/build.sbt
uploads/build.sbt

- sbt 0.13.13
- fix deprecation warnings https://github.com/sbt/sbt/pull/2716
- remove ls plugin

update build settings

---

project/common.scala

add scalacOptions for scaladoc

---

project/common.scala

Change groupId to ws.unfiltered, add authors.

---

library/src/test/scala/CookiesSpec.scala
oauth2/src/test/scala/AuthorizationSpec.scala
oauth2/src/test/scala/ProtectionSpec.scala
scalatest/src/main/scala/Hosted.scala
specs2/src/main/scala/Hosted.scala
specs2/src/main/scala/SecureClient.scala
specs2/src/main/scala/jetty/Served.scala
specs2/src/main/scala/netty/Served.scala

Hopefully this will improve the stability of the tests.

Shutdown okhttp3 client threads after tests.

---

json4s/src/test/scala/JsonpSpec.scala
oauth2/src/test/scala/AuthorizationSpec.scala
project/Dependencies.scala

https://github.com/etorreborre/specs2/issues/557

update specs2 3.8.9

---

netty/src/main/scala/bindings.scala

https://github.com/netty/netty/blob/netty-4.1.9.Final/codec-http/src/main/java/io/netty/handler/codec/http/HttpHeaders.java#L355

fix deprecation warnings

---

.travis.yml
project/common.scala

https://github.com/scala/scala/pull/5664#issuecomment-291163434

Revert "Scala 2.11.9"

---

.travis.yml
project/common.scala

- http://www.scala-lang.org/news/releases-1Q17.html
- https://github.com/scala/scala/releases/tag/v2.12.2
- https://github.com/scala/scala/releases/tag/v2.11.11

Scala 2.12.2, 2.11.11

---

jetty/src/main/scala/Server.scala

Pass on the RequestLogger dateformat

---

.travis.yml
project/build.properties
project/build.scala
project/common.scala

Hi, this is an attept to upgrade the build to sbt 1.0.2. Seems to be a minor change...

Migrate build to sbt1.0.2

---

filter-uploads/src/test/scala/UploadsSpec.scala
netty-uploads/src/test/scala/AsyncUploadSpec.scala
netty-uploads/src/test/scala/ChunkAggregatedUploadSpec.scala
netty-uploads/src/test/scala/CycleUploadSpec.scala

Write to separate files to avoid file system sync problems

---

netty/src/test/scala/FutureServerSpec.scala

This assigns a default 2 fixed deamon thread pool since the global might be used in other tests.
It seems to fix the intermittent test failures.

Using the global thread pool is dangerous

---

.travis.yml

according to https://github.com/travis-ci/travis-ci/issues/6483
PR added to see if matrix works

openjdk8 should work

---

filter/src/main/scala/bindings.scala
library/src/main/scala/kit/routes.scala
library/src/main/scala/request/cookies.scala
library/src/main/scala/request/params.scala
library/src/main/scala/response/cookies.scala
netty-server/src/main/scala/Server.scala
netty-server/src/main/scala/http.scala
netty/src/main/scala/bindings.scala
uploads/src/main/scala/request/uploads.scala

https://github.com/scala/scala/blob/5661290bfda0a08a60fb8df3ac60baafb55c0306/src/library/scala/collection/IterableOnce.scala#L465

use foldLeft instead of /:

---

jetty/src/main/scala/Server.scala
library/src/main/scala/kit/routes.scala
netty-server/src/main/scala/Server.scala
util/src/main/scala/servers.scala

deprecated since Scala 2.13
https://github.com/scala/scala/blob/e1d421667be8bc73ed0241fe7a24b36b162c51bd/src/library/scala/package.scala#L44-L47

use Iterable instead of Traversable

---

build.sbt
netty-server/src/main/scala/Engine.scala
netty-server/src/main/scala/Server.scala
netty-server/src/main/scala/http.scala

https://github.com/netty/netty/wiki/Native-transports

Add support for netty native transports (epoll/kqueue)

---

.scala-steward.conf
library/src/test/scala/HeadersSpec.scala
project/Dependencies.scala

Update netty to 4.1.44.Final.

---

directives/src/main/scala/directives/data/as/as.scala
directives/src/main/scala/directives/data/data.scala
filter-uploads/src/main/scala/request/uploads.scala
filter/src/main/scala/bindings.scala
jetty/src/main/scala/bindings.scala
jetty/src/main/scala/contexts.scala
library/src/main/scala/request/filtering.scala
library/src/main/scala/response/filtering.scala
library/src/main/scala/response/pass.scala
library/src/main/scala/response/writers.scala
netty-server/src/main/scala/Engine.scala
netty-server/src/main/scala/resources/resolvers.scala
netty-uploads/src/main/scala/request/uploads.scala
netty/src/main/scala/bindings.scala

add explicit type
